-- AlterTable
-- NOTE: Prisma's autogenerated diff also wanted to DROP INDEX
-- "Model_searchVector_idx" and ALTER COLUMN "searchVector" DROP DEFAULT —
-- both removed by hand. `searchVector` is a hand-added generated tsvector
-- column (see the 20260918151537_model_search_vector migration and the
-- `Unsupported("tsvector")?` comment in schema.prisma); Prisma's diff
-- engine doesn't understand GENERATED ALWAYS AS ... STORED columns and
-- proposes destructive-but-wrong changes to it on every new migration that
-- touches the Model table. Never accept those two statements verbatim.
ALTER TABLE "Model" ADD COLUMN     "noindex" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "seoDescription" TEXT,
ADD COLUMN     "seoTitle" TEXT;

-- AlterTable
ALTER TABLE "Tag" ADD COLUMN     "seoDescription" TEXT,
ADD COLUMN     "seoH1" TEXT,
ADD COLUMN     "seoIndexed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "seoTitle" TEXT;
